# Summary {.unnumbered}

This technical report is a companion to *Do School-Based Depression Prevention Programs Support Youth? Analyzing School-Based Interventions for Primary and Secondary Prevention of Depression*. It documents the methods and results of our rapid overview of systematic reviews with meta-analyses on the effectiveness of depression prevention interventions delivered directly to students in primary and secondary school settings. We searched PubMed, ProQuest Dissertations & Theses A&I, and Social Science Premium Collection for systematic reviews that included a meta-analysis on school-based depression prevention interventions. Two reviewers independently screened titles and abstracts, assessed full texts for eligibility, collected data, and critically appraised systematic reviews. To estimate effectiveness and explore sources of heterogeneity for interventions delivered directly to students during normal school hours, we conducted random effects meta-analyses using data from primary studies. We identified 24 eligible systematic reviews that included 450 primary studies overall; of these, 70 primary studies evaluated 84 active interventions delivered directly to 44,519 students during normal school hours. The majority of these 70 primary studies were cluster-randomized trials (33 studies, 51.4%) and took place in secondary school settings (39 studies, 55.7%). Students receiving depression prevention interventions had a 33% reduced risk of meeting criteria for a depression diagnosis relative to students in control groups (risk ratio = 0.67, 95% CI [0.48 to 0.93], 95% PI [0.27 to 1.66], $I^2$ = 67%, $\tau^2$ = 0.14). Students receiving depression prevention interventions also had lower depression symptoms relative to students in control groups (standardized mean difference = -0.12, 95% CI [-0.20, -0.04], 95% PI [-0.57, 0.33], $I^2$ = 71%, $\tau^2$ = 0.05). Interventions may have little to no average effect on anxiety symptoms, though the evidence is very uncertain. We could not conduct meta-analyses for all other outcomes. Based on the findings of previous reviews and our meta-analyses, school-based depression prevention interventions may reduce the risk of depression and severity of depression symptoms. However, we have concerns about risk of bias in this body of evidence, and effects vary considerably due to unidentified factors. The evidence is very uncertain about effects on other outcomes. While the evidence suggests schools are more likely than not to benefit from implementing these interventions in contexts similar to those in the review, users of this evidence should be aware that current research evidence suggests both positive and negative effects are possible.
