# Background

Depression is one of the most common mental health challenges facing children and adolescents today. Prior to the COVID-19 pandemic, prevalence rates of clinically elevated depression symptoms among youth in the United States were approximately 12.9% (Lu, 2019). Estimates derived during the COVID-19 pandemic era document markedly elevated rates of depression symptoms relative to those before the pandemic: 16.7% of youth ages 5-17 now experience clinically elevated symptoms of depression (Zablotsky et al., 2022). These elevations in depression and depression symptomology are observed in children and adolescents across the world, with a recent meta-analysis documenting that the global prevalence of clinically elevated depression for youth is 25.2% (Racine et al., 2021). In addition, findings from the National Survey of Children’s Health documented the lifetime prevalence of clinical (diagnosed) depression at 4.4% of U.S. children and adolescents ages 3-17 (Bitsko et al., 2022). However, prevalence of depression may increase throughout childhood and adolescence, as lifetime prevalence estimates for youth ages 12-17 are much higher—one estimate is 20.9% of U.S. adolescents having experienced clinical depression (Bitsko et al., 2022).
In the face of these alarmingly high rates of child and adolescent depression—especially following the onset of the COVID-19 pandemic—urgent calls have been made to prioritize the well-being and mental health of students in primary and secondary schools (Shim et al., 2022). Left unaddressed, depression exerts a host of negative outcomes for youth during childhood and adolescence—and extending into adulthood. These challenges include academic problems (Clayborne et al., 2019; Finning et al., 2019), alcohol and other drug use (Groenman et al., 2017), and family conflicts and relational challenges (Clayborne et al., 2019). Due to the high and increasing prevalence of depression among primary and secondary school students—and the negative developmental sequalae that often follow—depression is a serious public health issue in need of timely and effective prevention of its onset and consequences.

## Why It Is Important to Do This Review

School-based intervention is a promising approach to prevent youth depression (National Research Council, 2009). Schools are one of few settings where nearly all children and adolescents can be reached (Arora et al., 2019). The delivery of prevention services in the school setting importantly eliminates the many barriers that exist when families seek out mental health support, such as time, transportation, stigma around seeking mental health support, staffing shortages, and scheduling challenges (Werner-Seidler et al., 2021). Many systematic reviews and meta-analyses have assessed the effectiveness of school-based interventions to prevent depression (Ahlen et al., 2015; Caldwell et al., 2019a; Dray et al., 2017; Feiss et al., 2019; Rasing et al., 2017; Stockings et al., 2016; Werner-Seidler et al., 2021). An overview (also known as a “meta-review” or “umbrella review”) can systematically and coherently identify, collate, and synthesize these systematic reviews into a single document on the best available evidence to inform policy and practice decisions (Aromataris et al., 2020; Gates et al., 2022; Pollock et al., 2022). Several overviews of reviews have been published recently on interventions to prevent depression and depression episodes (Bellón et al., 2015; Hoare et al., 2021; Hu et al., 2020; Salazar de Pablo et al., 2021). While useful contributions to the literature, these reviews take a broader scope than youth and school-based interventions, resulting in limited information specific to these populations and settings. In addition, only one prior review included secondary prevention interventions in their syntheses, and none included evidence on outcomes beyond depression (such as student well-being and educational achievement) that are of crucial interest to educational stakeholders. Moreover, several systematic reviews on depression prevention interventions for youth are missing from these overviews (Johnstone et al., 2018; Phillips & Mychailyszyn, 2022; Tejada-Gallardo et al., 2020; Werner-Seidler et al., 2021; Zhang et al., 2022).

## Objectives

This technical report is a companion to *Do School-Based Depression Prevention Programs Support Youth? Analyzing School-Based Interventions for Primary and Secondary Prevention of Depression*. It documents the methods and results of our rapid overview of systematic reviews with meta-analyses on the effectiveness of depression prevention interventions delivered directly to students in primary and secondary school settings. Our overview aimed to assess the effects of school-based depression prevention interventions on depression diagnoses, subsyndromal depression, depressive symptoms, and non-depression outcomes related to student well-being and educational achievement. Our overview also explored whether these effects vary by methodological, demographic, and intervention characteristics. Our goal of this overview of reviews on school-based prevention interventions is to support the decisions of education stakeholders related to the development of policies, practice guidelines, and professional preparation and continuing development programs focused on youth behavioral health.
