# Conclusions

We identified 24 eligible systematic reviews that included 450 primary studies overall; of these, 70 primary studies evaluated 84 active interventions delivered directly to 44,519 students during normal school hours. Findings suggest that school-based depression prevention interventions may reduce the risk of depression diagnosis and severity of depression symptoms. Interventions delivered during school hours may have little to no average effect on anxiety symptoms, though the evidence is very uncertain. Our confidence in meta-analytic findings is reduced by the number of studies with plausible explanations other than differences in interventions received (i.e., risks of bias). For anxiety symptoms, our confidence is also reduced by imprecision (i.e., a confidence interval that includes average effects of both reduced and increased anxiety symptoms). Moreover, there is substantial unexplained heterogeneity in study effect estimates and wide prediction intervals. Consequently, while the evidence suggests schools implementing these interventions in contexts similar to those in the review are more likely than not to see improvements in depression diagnoses and symptoms, users of this evidence should be aware that current research evidence suggests both positive and negative effects are possible. We could not conduct meta-analyses for other tertiary outcomes. Strengths of this review include the use of explicit research questions and eligibility criteria, prospective registration of the review protocol, eligibility assessment and data collection in duplicate, use of established techniques to assess risk of bias, and use of meta-analytic techniques that include all (dependent) effect sizes reported in eligible primary studies (even when the exact form of the dependence is unknown). Potential ways to improve the strengths of this review are to supplement our literature search for systematic review (e.g., grey and non-English literature sources) and conduct our own supplemental search for primary studies.